AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  LambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: uk.co.thalumas.lambda.StreamLambdaHandler::handleRequest
      Runtime: java21
      CodeUri: target/demo-java-lambda-1.0-lambda-package.zip
      MemorySize: 1024
      Timeout: 10